Updated

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,28 +1,26 @@
 #!/usr/bin/env bash
-# check for command line argument
-
+# Checking for command-line argument
 if [ $# -lt 4 ]
 then
- 	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
- 	exit 1
+	  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	    exit 1
 fi
 
-# assign parameter to variables
+# Assigning Arguments to variables
 
 path_to_file=$1
 ip=$2
 username=$3
 path_to_ssh_key=$4
 
-# disable strict host key checking
 
-scp -o "StrictHostKeyChecking=no" -i $path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+# Disabling Strict Host Key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
-
-# check if file transfer was success
+# Checking if the transfer was successful
 if [ $? -eq 0 ]
 then
- 	echo "FILE TRANSFER SUCCESS"
-else
- 	echo "FILE TRANSFER UNSUCCESSFUL"
+	  echo "FILE TRANSFER WAS SUCCESS"
+  else
+	    echo "FILE TRANSFER FAILED"
 fi
